/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/initialScreen`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/levels` | `/levels`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/levels/start` | `/levels/start`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/levels/wudu` | `/levels/wudu`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/levels/fatiha` | `/levels/fatiha`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/levels/fatiha/secondScreen` | `/levels/fatiha/secondScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/levels/fatiha/thirdScreen` | `/levels/fatiha/thirdScreen`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/initialScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/levels` | `/levels`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/levels/start` | `/levels/start`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/levels/wudu` | `/levels/wudu`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/levels/fatiha` | `/levels/fatiha`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/levels/fatiha/secondScreen` | `/levels/fatiha/secondScreen`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/levels/fatiha/thirdScreen` | `/levels/fatiha/thirdScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/initialScreen${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/settings${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/levels${`?${string}` | `#${string}` | ''}` | `/levels${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/levels/start${`?${string}` | `#${string}` | ''}` | `/levels/start${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/levels/wudu${`?${string}` | `#${string}` | ''}` | `/levels/wudu${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/levels/fatiha${`?${string}` | `#${string}` | ''}` | `/levels/fatiha${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/levels/fatiha/secondScreen${`?${string}` | `#${string}` | ''}` | `/levels/fatiha/secondScreen${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/levels/fatiha/thirdScreen${`?${string}` | `#${string}` | ''}` | `/levels/fatiha/thirdScreen${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/initialScreen`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/levels` | `/levels`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/levels/start` | `/levels/start`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/levels/wudu` | `/levels/wudu`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/levels/fatiha` | `/levels/fatiha`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/levels/fatiha/secondScreen` | `/levels/fatiha/secondScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/levels/fatiha/thirdScreen` | `/levels/fatiha/thirdScreen`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
